Updated README.md
ovrclk/docs pull request #224
Opened 2021-08-16 15:08 UTC by Developer-piyush

I have updated readme and working on some more stuffs to  come up with excellent guides!
If there is any reward for this then here is my akash address:
akash1trhmdtnfd3tlltcxengcs9zwvhwt0mc3x7wmv7

2021-08-29 21:42 UTC, colinpollen requested changes
The start of these changes are in HTML and will not work in our markdown formatted file.

2021-08-31 05:27 UTC, Developer-piyush commented on README.md
> +<br />
No sir, it works in both html as well as markup! You can have a look at live changes of mine here: https://github.com/Developer-piyush/docs

2022-07-04 17:18 UTC, andy108369 commented on README.md
> +<br />
Can confirm, it does work https://github.com/ovrclk/docs/blob/b0d20b6772a0e702ae5432f260960d59cb8c2db9/README.md

2022-07-04 17:20 UTC, andy108369 commented
@Developer-piyush there have been multiple [updates](https://github.com/ovrclk/docs/commits/master/README.md) to the README.md file, mind rebasing your PR?

2022-08-09 06:30 UTC, closed without merging